### ISSUE TITLE
How to add cdn.clustrmaps with md

### ISSUE THREAD

**Issue by Shicheng-Guo** [mdekauwe/mdekauwe.github.io#2]
Hi Dr. Kauwe, 

I notice you are successfully assembled cdn.clustrmaps in your mdekauwe.github.io. I also want to do that, but met some problems. 

I didn't use index.html but use index.md as the main page.  Do you have any suggestion to add cdn.clustrmaps in index.md so that to have clustrmaps in my github.io? 

my github.io site: https://shicheng-guo.github.io/

{% for js in page.customjs %}
<script type="text/javascript" id="clustrmaps" src="//cdn.clustrmaps.com/map_v2.js?u=ucht&d=aPco3MWa80OUX4PipZdxfDGoBfQziq50CLbq759xSls"></script>
{% endfor %}

Thanks. 

Shicheng

**Comment by mdekauwe** [comment]
Hi Shicheng,

Honestly, I've got no idea how I did it, I think I hacked about at some point. Best I can suggest is to compare the files and see if you can spot anything... 

Sorry I can't be of more help
